### ISSUE TITLE
chebai does not run with the latest python version

### ISSUE THREAD

**Issue by sfluegel05** [ChEB-AI/python-chebai#66]
Currently, the latest python version compatible with chebai is `3.11`. This has been mentioned in https://github.com/ChEB-AI/python-chebai/issues/16 and is listed in the requirements.

## Todo
Find out
- why chebai does not run with python 3.12
- if this can be fixed (and how)

**Comment by sfluegel05** [comment]
I tried reproducing this with python 3.12.8, but had no problems during the installation. I would suggest to remove <3.12 from the requirements and add 3.12 to the tests.

However, I also tried 3.13.1, which fails with

```
      ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
```

I didn't find any information regarding this bug. Since fixing it seems to be outside the scope of our project, I will add <3.13 as a requirement for now.

Full output:
```
$ pip install -e .
Obtaining file:///C:/Users/S.Fl%C3%BCgel/PycharmProjects/python-chebai
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting certifi (from chebai==0.0.2.dev0)
  Using cached certifi-2024.12.14-py3-none-any.whl.metadata (2.3 kB)
Collecting idna (from chebai==0.0.2.dev0)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting joblib (from chebai==0.0.2.dev0)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting networkx (from chebai==0.0.2.dev0)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting numpy<2 (from chebai==0.0.2.dev0)
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 2
  ╰─> [35 lines of output]
      + C:\Users\S.Flügel\AppData\Local\Programs\Python\Python313\python.exe C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb\vendored-meson\meson\meson.
py setup C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9f
b\.mesonpy-wku65s9h -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb\.mesonpy-wku65s9h\meson-python-native-file.ini
      Traceback (most recent call last):
        File "C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb\vendored-meson\meson\mesonbuild\mesonmain.py", line 194, in run
          return options.run_func(options)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb\vendored-meson\meson\mesonbuild\msetup.py", line 358, in run
          app.generate()
          ~~~~~~~~~~~~^^
        File "C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb\vendored-meson\meson\mesonbuild\msetup.py", line 178, in generate
          env = environment.Environment(self.source_dir, self.build_dir, self.options)
        File "C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb\vendored-meson\meson\mesonbuild\environment.py", line 571, in __init__
          config = coredata.parse_machine_files(self.coredata.config_files)
        File "C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb\vendored-meson\meson\mesonbuild\coredata.py", line 1032, in parse_machine_files
          parser = MachineFileParser(filenames)
        File "C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb\vendored-meson\meson\mesonbuild\coredata.py", line 973, in __init__
          self.parser.read(filenames)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^
        File "C:\Users\S.Flügel\AppData\Local\Temp\pip-install-q6036aka\numpy_012b3945575848c4b5e9283f0a33d9fb\vendored-meson\meson\mesonbuild\coredata.py", line 960, in read
          return super().read(filenames, encoding)
                 ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\S.Flügel\AppData\Local\Programs\Python\Python313\Lib\configparser.py", line 735, in read
          self._read(fp, filename)
          ~~~~~~~~~~^^^^^^^^^^^^^^
        File "C:\Users\S.Flügel\AppData\Local\Programs\Python\Python313\Lib\configparser.py", line 1050, in _read
          ParsingError._raise_all(self._read_inner(fp, fpname))
                                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
        File "C:\Users\S.Flügel\AppData\Local\Programs\Python\Python313\Lib\configparser.py", line 1058, in _read_inner
          for st.lineno, line in enumerate(map(Line, fp), start=1):
                                 ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen codecs>", line 325, in decode
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 37: invalid start byte

      ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
